server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${DB_NAME:clock_in}?characterEncoding=utf-8&amp&serverTimezone=UTC&amp&allowPublicKeyRetrieval=true&useSSL=false
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 500000
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL:update}

  web:
    resources:
      static-locations: classpath:/static/
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 3MB
mybatis-plus:
  mapper-locations: classpath:mapper/*/*Mapper.xml

file:
  upload:
    path: ${UPDATE_PATH:C:/TemplateUploadFIle/}